---

- name: 'initialise Vault (solo)'
  command: /usr/local/bin/init-vault.sh
  when:
  - vault_role == 'server'
  - "'vault_solo' in group_names"
  register: reg_vault_init
  changed_when:
  - reg_vault_init.rc != 99
  failed_when:
  - reg_vault_init.rc != 0
  - reg_vault_init.rc != 99
  become: true
  tags:
  - ct-vaultmanager

- name: 'fetch files from primary (1/2)'
  fetch:
    src: /var/tmp/vault/keys
    dest: /var/tmp/vault-keys
    flat: true
  when:
  - vault_role == 'server'
  - "'vault_solo' in group_names"
  become: true
  tags:
  - ct-vaultmanager

- name: 'fetch files from primary (2/2)'
  fetch:
    src: /var/tmp/vault/token
    dest: /var/tmp/vault-token
    flat: true
  when:
  - vault_role == 'server'
  - "'vault_solo' in group_names"
  become: true
  tags:
  - ct-vaultmanager

- name: 'push files to secondaries'
  copy:
    src: /var/tmp/vault-keys
    dest: /var/tmp/vault/keys
    group: root
    mode: '0600'
    owner: root
  no_log: true
  when:
  - vault_role == 'server'
  - "'vault_solo' not in group_names"
  become: true
  tags:
  - ct-vaultmanager

- name: 'unseal the Vault'
  command: /usr/local/bin/unseal-vault.sh
  when: vault_role == 'server'
  register: reg_vault_unseal
  become: true
  changed_when: reg_vault_unseal.rc != 99
  failed_when:
  - reg_vault_unseal.rc != 0
  - reg_vault_unseal.rc != 99
  tags:
  - ct-vaultmanager

- name: 'prepare the Vault (solo)'
  command: /usr/local/bin/prepare-vault.sh
  when:
  - vault_role == 'server'
  - "'vault_solo' not in group_names"
  register: reg_vault_prepare
  become: true
  changed_when: reg_vault_prepare.rc != 99
  failed_when:
  - reg_vault_prepare.rc != 0
  - reg_vault_prepare.rc != 99
  tags:
  - ct-vaultmanager

- name: 'fetch Nomad file (solo)'
  fetch:
    src: /var/tmp/vault/vars-pri-nomad.yml
    dest: vars-pri-nomad.yml
    flat: true
  when:
  - vault_role == 'server'
  - "'vault_solo' in group_names"
  become: true
  tags:
  - ct-vaultmanager

- name: 'clean up temp files'
  file:
    state: absent
    path: '{{item}}'
  loop: ['/var/tmp/vault/keys', '/var/tmp/vault/token']
  become: true
  when:
  - vault_role == 'server'
  - "'vault_solo' not in group_names"
  tags:
  - ct-vaultmanager

# --------------------------------
...
